eureka:
  client:
    serviceUrl:
      # \u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3\u7684\u5730\u5740
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    ip-address: 127.0.0.1
spring:
  application:
    name: client
server:
  port: 8080
